import type { DiagramResources } from "../types"

export const generateReadMeObject = (stackName: string, resources: DiagramResources) => {
  const lambdaSection = resources.lambdaFunctions.length > 0
    ? `
## Lambda functions

This project includes ${resources.lambdaFunctions.length} Lambda function(s) under the \`lib/functions/\` directory.

- **Node.js** functions use \`NodejsFunction\` and are bundled automatically during \`cdk deploy\`.
- **Python** functions use \`lambda.Code.fromAsset\` with an \`index.py\` handler.
- **Go** functions use \`PROVIDED_AL2023\`. Build the \`bootstrap\` binary before deploy:

\`\`\`bash
npm run build:lambda:go
\`\`\`

Or build a specific function:

\`\`\`bash
cd lib/functions/my-function && make build
\`\`\`
`
    : ""

  return `# ${stackName}

AWS CDK project generated by ArchDraw.

This is a blank project for CDK development with TypeScript.

The \`cdk.json\` file tells the CDK Toolkit how to execute your app.
${lambdaSection}
## Useful commands

* \`npm run build\`   compile typescript to js
* \`npm run watch\`   watch for changes and compile
* \`npm run test\`    perform the jest unit tests
* \`npx cdk deploy\`  deploy this stack to your default AWS account/region
* \`npx cdk diff\`    compare deployed stack with current state
* \`npx cdk synth\`   emits the synthesized CloudFormation template
`
}
