import { toTerraformResourceName } from "../sanitizeNames"
import type { DiagramResources, ProjectFile } from "../types"

function escapeTerraformString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
}

function resolveTopicName(topicName: string, topicType: "standard" | "fifo", fallback: string): string {
  const trimmed = topicName.trim()
  return trimmed || (topicType === "fifo" ? `${fallback}.fifo` : fallback)
}

function renderSnsTopic(topic: DiagramResources["snsTopics"][number], index: number): string {
  const resourceName = toTerraformResourceName(topic.topicName, `sns_topic_${index + 1}`)
  const topicName = resolveTopicName(topic.topicName, topic.topicType, `topic-${index + 1}`)
  const fifoLine = topic.topicType === "fifo" ? "\n  fifo_topic = true" : ""

  return `resource "aws_sns_topic" "${resourceName}" {
  name = "${escapeTerraformString(topicName)}"${fifoLine}
}`
}

function renderSnsOutput(topic: DiagramResources["snsTopics"][number], index: number): string {
  const resourceName = toTerraformResourceName(topic.topicName, `sns_topic_${index + 1}`)
  const outputName = `${resourceName}_arn`

  return `output "${outputName}" {
  description = "ARN of SNS topic ${topic.topicName || `topic-${index + 1}`}"
  value       = aws_sns_topic.${resourceName}.arn
}`
}

export function generateTerraformProject(stackName: string, resources: DiagramResources): ProjectFile[] {
  const files: ProjectFile[] = [
    {
      relativePath: "main.tf",
      content: `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
`,
    },
    {
      relativePath: "variables.tf",
      content: `variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}
`,
    },
  ]

  if (resources.snsTopics.length > 0) {
    const snsBlocks = resources.snsTopics.map(renderSnsTopic).join("\n\n")
    files.push({
      relativePath: "sns.tf",
      content: `${snsBlocks}\n`,
    })

    const outputBlocks = resources.snsTopics.map(renderSnsOutput).join("\n\n")
    files.push({
      relativePath: "outputs.tf",
      content: `${outputBlocks}\n`,
    })
  }

  files.push({
    relativePath: "README.md",
    content: `# ${stackName}

Terraform project generated by ArchDraw.

## Resources

${resources.snsTopics.length > 0 ? `- ${resources.snsTopics.length} SNS topic(s)\n` : "- No resources from the diagram yet\n"}
## Usage

\`\`\`bash
terraform init
terraform plan
terraform apply
\`\`\`
`,
  })

  return files
}
