import { buildTerraformContext } from "./buildTerraformContext"
import { generateTerraformLambdaAssetFiles } from "./lambda/generateTerraformLambdaAssetFiles"
import { renderLambdaFunctions, renderLambdaOutputs } from "./infra/renderLambdaResources"
import { renderSnsTopicOutputs, renderSnsTopics } from "./infra/renderSnsResources"
import { renderSqsDlqs, renderSqsOutputs, renderSqsQueues } from "./infra/renderSqsResources"
import { renderAllSubscriptions } from "./infra/renderSubscriptionResources"
import type { DiagramResources, ProjectFile } from "../types"

function buildReadme(stackName: string, resources: DiagramResources): string {
  const resourceLines = [
    resources.snsTopics.length > 0 ? `- ${resources.snsTopics.length} SNS topic(s)` : null,
    resources.lambdaFunctions.length > 0 ? `- ${resources.lambdaFunctions.length} Lambda function(s)` : null,
    resources.sqsQueues.length > 0 ? `- ${resources.sqsQueues.length} SQS queue(s)` : null,
    resources.sqsDlqs.length > 0 ? `- ${resources.sqsDlqs.length} SQS DLQ(s)` : null,
    resources.snsSqsSubscriptions.length > 0 ? `- ${resources.snsSqsSubscriptions.length} SNS → SQS subscription(s)` : null,
    resources.snsLambdaSubscriptions.length > 0 ? `- ${resources.snsLambdaSubscriptions.length} SNS → Lambda subscription(s)` : null,
    resources.sqsLambdaEventSources.length > 0 ? `- ${resources.sqsLambdaEventSources.length} SQS → Lambda event source(s)` : null,
  ].filter(Boolean)

  const lambdaSection = resources.lambdaFunctions.some((lambdaFunction) => lambdaFunction.language === "go")
    ? `
## Lambda functions (Go)

Build Go Lambda binaries before deploy:

\`\`\`bash
find functions -name Makefile -execdir make build \\;
\`\`\`
`
    : resources.lambdaFunctions.length > 0
      ? `
## Lambda functions

Lambda source code lives under \`functions/\`. Terraform packages each function into \`build/\` during plan/apply.
`
      : ""

  return `# ${stackName}

Terraform project generated by ArchDraw.

## Resources

${resourceLines.length > 0 ? resourceLines.join("\n") : "- No resources from the diagram yet"}
${lambdaSection}
## Usage

\`\`\`bash
terraform init
terraform plan
terraform apply
\`\`\`
`
}

function buildGitignore(resources: DiagramResources): string {
  const goBuildArtifacts = resources.lambdaFunctions.some((lambdaFunction) =>
    lambdaFunction.language === "go",
  )
    ? `
functions/**/cmd/bootstrap
`
    : ""

  return `.terraform/
*.tfstate
*.tfstate.*
crash.log
crash.*.log
build/
${goBuildArtifacts}`
}

export function generateTerraformProject(stackName: string, resources: DiagramResources): ProjectFile[] {
  const context = buildTerraformContext(resources)
  const files: ProjectFile[] = [
    {
      relativePath: "main.tf",
      content: `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
`,
    },
    {
      relativePath: "variables.tf",
      content: `variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}
`,
    },
    {
      relativePath: "README.md",
      content: buildReadme(stackName, resources),
    },
    {
      relativePath: ".gitignore",
      content: buildGitignore(resources),
    },
    ...generateTerraformLambdaAssetFiles(resources),
  ]

  if (resources.snsTopics.length > 0) {
    files.push({
      relativePath: "sns.tf",
      content: `${renderSnsTopics(resources, context)}\n`,
    })
  }

  if (resources.sqsDlqs.length > 0 || resources.sqsQueues.length > 0) {
    const sqsBlocks = [
      renderSqsDlqs(resources, context),
      renderSqsQueues(resources, context),
    ].filter(Boolean).join("\n\n")

    files.push({
      relativePath: "sqs.tf",
      content: `${sqsBlocks}\n`,
    })
  }

  if (resources.lambdaFunctions.length > 0) {
    files.push({
      relativePath: "lambda.tf",
      content: `${renderLambdaFunctions(resources, context)}\n`,
    })
  }

  const subscriptions = renderAllSubscriptions(resources, context)
  if (subscriptions) {
    files.push({
      relativePath: "subscriptions.tf",
      content: `${subscriptions}\n`,
    })
  }

  const outputs = [
    renderSnsTopicOutputs(resources, context),
    renderSqsOutputs(resources, context),
    renderLambdaOutputs(resources, context),
  ].filter(Boolean).join("\n\n")

  if (outputs) {
    files.push({
      relativePath: "outputs.tf",
      content: `${outputs}\n`,
    })
  }

  return files
}
